### ISSUE TITLE
Switch from ref strings to ref callbacks

### ISSUE THREAD

**Issue by kikoruiz** [SUI-Components/sui-autocompleted#17]
We should move from ref strings (e.g.: https://github.com/SUI-Components/sui-autocompleted/blob/master/src/sui-autocompleted/index.jsx#L142) to ref callbacks because it's a better practice and strings might be set as deprecated in a future, right now they're considered legacy: https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute.

This change must be a major beacuse we can break the API of that referenced element in any high-order component that's using it.

**Comment by midudev** [comment]
👍
