### ISSUE TITLE
Set component input name property from outside

### ISSUE THREAD

**Issue by zecafa** [SUI-Components/sui-autocompleted#18]
I'm using the component in a form, and i would like to manage it as a normal input field.
I would like to be able to set the input name property from the container, so i could access its value like other form fields.
What do you think about it?

**Comment by midudev** [comment]
Hi @zecafa, sorry for the late response as we had a lot of meetings and different restructuring of teams. Is it fixed? Don't you need that anymore? :) Have you found another approeach?

**Comment by zecafa** [comment]
Hi @miduga. 
Yes, finally i choose another approach. Thanks for answering

**Comment by midudev** [comment]
Indeed. You're welcome! ;)
