### ISSUE TITLE
Don't select the first option by default.

### ISSUE THREAD

**Issue by arturoscmspain** [SUI-Components/sui-autocompleted#19]
Don't select the first option by default. As when you do you click on the button will always select the first default. And the free text is never searched.
(Sergi knows the subject)

**Comment by carlosvillu** [comment]
Maybe we can use a flag property to avoid this default behaviour w/out broken the public API

**Comment by midudev** [comment]
I think that what @carlosvillu said would be the better approach. We can add a prop to the component selectFirstByDefault. Its value by default should be `true` in order to avoid breaking the public API. Could you implement it @arturoscmspain or want us to try to chip it in?
